# Generated by build.rs from crates/gam-terms/src/analytic_penalties/manifest.rs.
PENALTY_MANIFEST = (
    {
        "kind": "isometry",
        "rust": "Isometry:IsometryPenalty",
        "python": "IsometryPenalty",
    },
    {
        "kind": "sparsity",
        "rust": "Sparsity:SparsityPenalty",
        "python": "SparsityPenalty",
    },
    {
        "kind": "softmax_assignment_sparsity",
        "rust": "SoftmaxAssignmentSparsity:SoftmaxAssignmentSparsityPenalty",
        "python": "SoftmaxAssignmentSparsityPenalty",
    },
    {
        "kind": "ordered_beta_bernoulli",
        "rust": "OrderedBetaBernoulli:OrderedBetaBernoulliPenalty",
        "python": "OrderedBetaBernoulliPenalty",
    },
    {
        "kind": "ard",
        "rust": "Ard:ARDPenalty",
        "python": "ARDPenalty",
    },
    {
        "kind": "topk_activation",
        "rust": "TopKActivation:TopKActivationPenalty",
        "python": "TopKActivationPenalty",
    },
    {
        "kind": "smooth_threshold",
        "rust": "SmoothThreshold:SmoothThresholdPenalty",
        "python": "SmoothThresholdPenalty",
    },
    {
        "kind": "total_variation",
        "rust": "TotalVariation:TotalVariationPenalty",
        "python": "TotalVariationPenalty",
    },
    {
        "kind": "harmonic_roughness",
        "rust": "HarmonicRoughness:HarmonicRoughnessPenalty",
        "python": "HarmonicRoughnessPenalty",
    },
    {
        "kind": "nuclear_norm",
        "rust": "NuclearNorm:NuclearNormPenalty",
        "python": "NuclearNormPenalty",
    },
    {
        "kind": "block_sparsity",
        "rust": "BlockSparsity:BlockSparsityPenalty",
        "python": "BlockSparsityPenalty",
    },
    {
        "kind": "mechanism_sparsity",
        "rust": "MechanismSparsity:MechanismSparsityPenalty",
        "python": "MechanismSparsityPenalty",
    },
    {
        "kind": "monotonicity",
        "rust": "Monotonicity:ShapeMonotonicityPenalty",
        "python": "MonotonicityPenalty",
    },
    {
        "kind": "nested_prefix",
        "rust": "NestedPrefix:NestedPrefixPenalty",
        "python": "NestedPrefixPenalty",
    },
    {
        "kind": "row_precision_prior",
        "rust": "RowPrecisionPrior:RowPrecisionPriorPenalty",
        "python": "AuxConditionalPriorPenalty",
    },
    {
        "kind": "ivae_ridge_mean_gauge",
        "rust": "IvaeRidgeMeanGauge:IvaeRidgeMeanGauge",
        "python": "IvaeRidgeMeanGauge",
    },
    {
        "kind": "parametric_row_precision_prior",
        "rust": "ParametricRowPrecisionPrior:ParametricRowPrecisionPriorPenalty",
        "python": "ParametricAuxConditionalPriorPenalty",
    },
    {
        "kind": "scad_mcp",
        "rust": "ScadMcp:ScadMcpPenalty",
        "python": "ScadMcpPenalty",
    },
    {
        "kind": "block_orthogonality",
        "rust": "BlockOrthogonality:BlockOrthogonalityPenalty",
        "python": "BlockOrthogonalityPenalty",
    },
    {
        "kind": "decoder_incoherence",
        "rust": "DecoderIncoherence:DecoderIncoherencePenalty",
        "python": "DecoderIncoherencePenalty",
    },
    {
        "kind": "orthogonality",
        "rust": "Orthogonality:OrthogonalityPenalty",
        "python": "OrthogonalityPenalty",
    },
    {
        "kind": "sheaf_consistency",
        "rust": "SheafConsistency:SheafConsistencyPenalty",
        "python": "SheafConsistencyPenalty",
    },
)
